### PR TITLE
Refactoring mail service into react query hook

### LINKED ISSUE #41: Refactor the mail service methods into react query hooks
This issue requires that the two methods present in the `mail.service.js` file be moved to a redux/hooks/mail/index.js file.

Acceptance Criteria:
1. The send mail and delete mail functions should be wrapped in the react query hooks
2. The react hooks created should be implemented with best and standard practices
3. The react hooks created should return the standard useMutation query response props

### PR DESCRIPTION
**Pull request by joshdev12**
Pls review

### CODE REVIEW

**Comment by Harrylever** [comment]
Rename this PR to something more descriptive. __`Refactor`__ is not good enough.

Can you get inspiration from the issue title: [Refactor the mail service methods into react query hooks](https://github.com/ZIDTHEGEEK/Team-Alpha-s-frontend-repository-/issues/41)

**Review by Harrylever — CHANGES_REQUESTED** [review]
Rename this PR to something more descriptive. __`Refactor`__ is not good enough.

Can you get inspiration from the issue title: [Refactor the mail service methods into react query hooks](https://github.com/ZIDTHEGEEK/Team-Alpha-s-frontend-repository-/issues/41)

**Comment by Harrylever** [comment]
Screenshot From 2024-12-04 06-04-57

From the image above you would see the dropped down list of issues under the development tab. Kindly identify and select your issue from the list so it would be closed once this PR is merged.

**Comment by joshdev12** [comment]
Done

**Review by Harrylever — APPROVED** [review]

**Pull request merged**
